
def generate_proposal(client_type, issue, product, usage_notes):
    return f"""
# Momar Customized Maintenance Proposal

## Client Type:
{client_type}

## Identified Problem:
{issue}

## Recommended Product:
**{product}**

### Usage Instructions:
{usage_notes}

---

This proposal is auto-generated by Momar's AI Assistant. Please verify all usage guidance with your safety officer before application.
"""
